### ISSUE TITLE
bootstrap4 support

### ISSUE THREAD

**Issue by ghost** [angelozerr/tern-bootstrap#1]
fyi --

with bootstrap4 on its way, snippets and autocompletion for Atom editor is available & "up to date",
https://atom.io/packages/atom-bootstrap4
perhaps informative for eventual tern BS4 update

**Comment by angelozerr** [comment]
@pgnd you would like to have a support for bootstrap 4 with tern?

If it that, perhaps we should have 2 projects : tern-bootstrap3 and tern-bootstrap4?

**Comment by ghost** [comment]
@angelozerr

I'm guessing it won't be just me ... BS community is big. Even tho it's just in 'alpha' at the moment, BS4 is moving fast.  And, clearly, there's at least one editor already supporting expansions for it.

From a practical standpoint, BS3 isn't going away for quite awhile; BS4 otoh has lots of early eyes already on the project.

If BS 3&4 support continues to be a tern project interest, then splitting the projects makes sense.

I have not looked in detail yet at tern's BS support.  Is it HTML/CSS-expansion only?  Or also the JS classes?

**Comment by angelozerr** [comment]
> Is it HTML/CSS-expansion only?

No tern is just for JavaScript.

> Or also the JS classes?

Yes, it's that. 

I will wait to support bootstrap 4, if there are several users who want to have this support.

**Comment by ghost** [comment]
We'll look elsewhere, then.  Thanks!
